[package]
name = "skdlr-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "skdlr-tui"
path = "src/main.rs"

[dependencies]
skdlr-core.workspace = true
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
env_logger.workspace = true
log.workspace = true
ratatui.workspace = true
serde.workspace = true
tokio.workspace = true

[lints]
workspace = true
